//*****************************************************************************
//
// pinmux.c - Function to write the generated pin mux values to the appropriate
//            registers.
// Created using TI Pinmux 4.0.1543  on 1/6/2021 at 7:10:04 PM.
//
//*****************************************************************************
//
// Copyright (C) 2017 Texas Instruments Incorporated - http://www.ti.com/
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
//
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the
//   distribution.
//
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
//*****************************************************************************
//
// NOTE!! This file uses driverlib register macros from C2000Ware.
// This function is provided for your convenience and to serve as an example
// of the use of the generated header file, but its use is not required.
//
// To download C2000Ware:  http://www.ti.com/tool/C2000Ware
//
//*****************************************************************************

#include "driverlib.h"
#include "pinmux.h"

//*****************************************************************************
//
// Configures the pin mux registers, using the generated register values.
//
// This function writes the values generated by the pin mux tool to their
// corresponding GPIO control registers. These generated values should be found
// in the generated "pinmux.h."
//
//*****************************************************************************
void
GPIO_setPinMuxConfig(void)
{
    uint32_t lockValA;
    uint32_t lockValB;
    uint32_t lockValC;
    uint32_t lockValD;

    EALLOW;

    //
    // Save the current value of the GPIO lock registers
    //
    lockValA = HWREG(GPIOCTRL_BASE + GPIO_O_GPALOCK);
    lockValB = HWREG(GPIOCTRL_BASE + GPIO_O_GPBLOCK);
    lockValC = HWREG(GPIOCTRL_BASE + GPIO_O_GPCLOCK);
    lockValD = HWREG(GPIOCTRL_BASE + GPIO_O_GPDLOCK);

    //
    // Unlock the GPIO control registers
    //
    HWREG(GPIOCTRL_BASE + GPIO_O_GPALOCK) = 0x00000000;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPBLOCK) = 0x00000000;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPCLOCK) = 0x00000000;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPDLOCK) = 0x00000000;

    //
    // Clear the mux register fields that are about to be changed
    //
    HWREG(GPIOCTRL_BASE + GPIO_O_GPAGMUX1)	&= ~GPAMUX1_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPAGMUX2)	&= ~GPAMUX2_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPAMUX1)	&= ~GPAMUX1_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPAMUX2)	&= ~GPAMUX2_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPBGMUX1)	&= ~GPBMUX1_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPBGMUX2)	&= ~GPBMUX2_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPBMUX1)	&= ~GPBMUX1_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPBMUX2)	&= ~GPBMUX2_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPCGMUX1)	&= ~GPCMUX1_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPCGMUX2)	&= ~GPCMUX2_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPCMUX1)	&= ~GPCMUX1_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPCMUX2)	&= ~GPCMUX2_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPDGMUX1)	&= ~GPDMUX1_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPDMUX1)	&= ~GPDMUX1_MASK;

    //
    // Write pin muxing to mux registers
    //
    HWREG(GPIOCTRL_BASE + GPIO_O_GPAGMUX1)	|=  GPAGMUX1_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPAGMUX2)	|=  GPAGMUX2_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPAMUX1)	|=  GPAMUX1_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPAMUX2)	|=  GPAMUX2_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPBGMUX1)	|=  GPBGMUX1_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPBGMUX2)	|=  GPBGMUX2_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPBMUX1)	|=  GPBMUX1_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPBMUX2)	|=  GPBMUX2_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPCGMUX1)	|=  GPCGMUX1_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPCGMUX2)	|=  GPCGMUX2_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPCMUX1)	|=  GPCMUX1_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPCMUX2)	|=  GPCMUX2_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPDGMUX1)	|=  GPDGMUX1_VALUE;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPDMUX1)	|=  GPDMUX1_VALUE;

    //
    // Write pin analog mode select to registers
    //
    HWREG(GPIOCTRL_BASE + GPIO_O_GPBAMSEL)	&= ~GPBAMSEL_MASK;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPBAMSEL)	|= GPBAMSEL_VALUE;

    //
    // Restore GPIO lock register values
    //
    HWREG(GPIOCTRL_BASE + GPIO_O_GPALOCK) = lockValA;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPBLOCK) = lockValB;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPCLOCK) = lockValC;
    HWREG(GPIOCTRL_BASE + GPIO_O_GPDLOCK) = lockValD;

    EDIS;
}
