#ifndef CAN_MODULEDEFS_H_
#define CAN_MODULEDEFS_H_

// Software revision in CAN format of the firmware
#define SOFTWARE_VERSION_IN_CAN_FORMAT 									0x0106

//	General CAN Defs
#define	CAN_MESSAGE_RECEIVED		1
#define	EXTENDED_IDENTIFIER			1
#define	NO_MASKING_FOR_IDE			0
#define TRANSMIT_MAILBOX			0
#define RECEIVE_MAILBOX				1
#define MSG_IDE_MASK				0x1FFFFFFF
#define CLEAR_RESPONSE_EXTENSION_NIBBLE									0xFFFFFFE0
#define BLANK						255
#define MODEL_TO_BASE_ID_LEFT_SHIFT_FACTOR								16
#define ADDRESS_TO_BASE_ID_LEFT_SHIFT_FACTOR							8
#define MBOX16_TX_BUFFER_NOT_EMPTY	ECanaMboxes.MBOX16.MDL.byte.BYTE0 != 0
#define	ONE_CRORTH_PLACE			10000000
#define	TEN_LAKTH_PLACE				1000000
#define	ONE_LAKTH_PLACE				100000
#define	TEN_THOUSANDTH_PLACE		10000
#define	ONE_THOUSANDTH_PLACE		1000
#define	ONE_HUNDREDTH_PLACE			100
#define	TENTH_PLACE					10

#define CLEAR_RMP					1
#define CAN_ACK_ERROR				1
#define RESET_TRANSMISSION_REQUEST	1
#define ACKNOWLEDGE_CAN_ERROR_FLAG	1

// Mailbox Message ID
#define MBOX15_BASE_MSG_ID			0x10000004
#define MBOX14_BASE_MSG_ID			0x11000004
#define MBOX13_BASE_MSG_ID			0x11100004

// General msg IDs used for msg id creation
#define CAN_BASE_ID_FOR_USER_SM_COM										0x10000000
#define CAN_BASE_ID_FOR_PRODUCT											0x01000000
#define CAN_BASE_ID_FOR_FAMILY											0x00100000
#define CAN_BASE_ID_FOR_GLOBAL_MESSAGES									0x00000004
#define CAN_BASE_ID_FOR_CALIBRATION_MESSAGES							0x00000008
#define CAN_BASE_ID_FOR_OUTPUT_CONTROL_MESSAGES							0x00000010
#define CAN_BASE_ID_FOR_STATE_CONTROL_MESSAGES							0x00000018
#define CAN_BASE_ID_FOR_QUERY_TYPE_MESSAGES								0x00000020
#define CAN_BASE_ID_FOR_GENERAL_RESPONSES								0x00000040
#define CAN_BASE_ID_FOR_RESPONSE_TO_QUERIES								0x00000060
#define CAN_BASE_ID_FOR_TRANSMIT_MBOX									0x00000000
#define CAN_BASE_ID_FOR_SRQ												0x00000001
 
// Mailbox Message IDE Masks in LAMI register
#define MBOX15_MSG_ID_MASK			0x00000003
#define MBOX14_MSG_ID_MASK			0x00000003
#define MBOX13_MSG_ID_MASK			0x00000003
#define MBOX12_MSG_ID_MASK			0x00000003
#define MBOX11_MSG_ID_MASK			0x00000007
#define MBOX10_MSG_ID_MASK			0x00000007
#define MBOX9_MSG_ID_MASK			0x00000003
#define MBOX8_MSG_ID_MASK			0x00000003

// Mailbox IDE extensions 
#define SINGLE_BYTE_EXTENSION											0x00
#define PROGRAM_VOLTAGE_EXENSION										0x01
#define PROGRAM_CURRENT_EXENSION										0x02
#define FAULT_STATUS                                                    0x03

#define PROGRAM_OVP_EXTENSION											0x03
#define PROGRAM_UVL_EXTENSION											0x04
#define CALIBRATION_DATE_EXTENSION										0x01
#define MEASURED_VOLTAGE_PARAMS_EXTENSION								0x02
#define MEASURED_CURRENT_PARAMS_EXTENSION								0x03

// Response Extensions
#define RESPONSE_MBOX_PROGRAMMED_PARAMS_EXTENSION						0x01
#define RESPONSE_MBOX_OUTPUT_PARAMS_EXTENSION							0x02
#define RESPONSE_RATED_PARAMS_EXTENSION									0x03
#define RESPONSE_SPECIFIED_PARAMS_EXTENSION								0x04
#define RESPONSE_MBOX_SET_LIMITS_EXTENSION								0x05
#define RESPONSE_MBOX_VOLTAGE_CAL_PARAMS_EXTENSION						0x06
#define RESPONSE_MBOX_CURRENT_CAL_PARAMS_EXTENSION						0x07
#define RESPONSE_MBOX_VOLTAGE_DISPLAY_CAL_PARAMS_EXTENSION				0x08
#define RESPONSE_MBOX_CURRENT_DISPLAY_CAL_PARAMS_EXTENSION				0x09
#define RESPONSE_PSU_STATE_SET_1_EXTENSION								0x0A
#define RESPONSE_PSU_STATE_SET_2_EXTENSION								0x0B
#define RESPONSE_INTERNAL_PSU_REGISTERS_EXTENSION						0x0C
#define RESPONSE_ENABLE_REGISTERS_EXTENSION								0x0D
#define RESPONSE_EVENT_REGISTERS_EXTENSION								0x0E
#define RESPONSE_MBOX_PSU_ONBOARD_TEMPERATURE_EXTENSION					0x0F
#define RESPONSE_DATE_OF_CALIBRATION									0x10
#define RESPONSE_FIRMWARE_REVISION										0x11

// Data Received Check
#define ENARKA_GLOBAL_MESSAGES_RECEIVED									ECanaShadow.CANRMP.bit.RMP15 == CAN_MESSAGE_RECEIVED
#define PSU_GLOBAL_MESSAGES_RECEIVED									ECanaShadow.CANRMP.bit.RMP14 == CAN_MESSAGE_RECEIVED
#define GLOBAL_1U_MESSAGES_RECEIVED										ECanaShadow.CANRMP.bit.RMP13 == CAN_MESSAGE_RECEIVED
#define MODEL_SPECIFIC_GLOBAL_MESSAGES_RECEIVED							ECanaShadow.CANRMP.bit.RMP12 == CAN_MESSAGE_RECEIVED
#define MESSAGE_RECEIVED_IN_THE_CALIBRATION_MAILBOX						ECanaShadow.CANRMP.bit.RMP11 == CAN_MESSAGE_RECEIVED
#define OUTPUT_CONTROL_MESSAGES_RECEIVED								ECanaShadow.CANRMP.bit.RMP10 == CAN_MESSAGE_RECEIVED
#define STATE_CONTROL_MESSAGES_RECEIVED									ECanaShadow.CANRMP.bit.RMP9 == CAN_MESSAGE_RECEIVED
#define MESSAGE_RECEIVED_IN_THE_QUERY_MAILBOX							ECanaShadow.CANRMP.bit.RMP8 == CAN_MESSAGE_RECEIVED

// Can Data constants
		// Ouptut Related -- 0xAX,0xBX
#define CAN_OUTPUT_OFF_BYTE												0x00
#define	CAN_OUTPUT_ON_BYTE												0xAA
#define CAN_FEC_ON_BYTE                                                 0xBB
#define	CAN_BYTE_TO_RESET_PSU_TO_SAFE_STATE								0xA0
#define CAN_BYTE_TO_SAVE_SETTINGS										0xA1
#define CAN_BYTE_TO_RECALL_SETTINGS										0xA2
#define CAN_BYTE_TO_SET_VOLTAGE_MINIMUM									0xA3
#define CAN_BYTE_TO_SET_VOLTAGE_MAXIMUM									0xA4
#define CAN_BYTE_TO_SET_CURRENT_MINIMUM									0xA5
#define CAN_BYTE_TO_SET_CURRENT_MAXIMUM									0xA6
#define CAN_BYTE_TO_SET_OVP_MINIMUM										0xA7
#define CAN_BYTE_TO_SET_OVP_MAXIMUM										0xA8
#define CAN_BYTE_TO_SET_UVL_MINIMUM										0xA9
#define CAN_BYTE_TO_SET_UVL_MAXIMUM										0xAB
#define CAN_BYTE_TO_SET_FOLDBACK_MODE									0xAC
#define CAN_BYTE_TO_SET_PROTECTION_DELAY								0xAD
#define CAN_BYTE_TO_SET_PSU_ACCESS_MODE									0xAE
#define CAN_BYTE_TO_SET_START_MODE										0xAF

		// State Related -- 0xCX			
#define CAN_BYTE_TO_CLEAR_EVENT_REGISTERS								0xCE
#define CAN_BYTE_TO_ENABLE_POWER_ON_STATUS_CLEAR						0xC0
#define CAN_BYTE_TO_DISABLE_POWER_ON_STATUS_CLEAR						0xC1
#define CAN_BYTE_TO_ENABLE_CAN_SRQ										0xCC
#define CAN_BYTE_TO_DISABLE_CAN_SRQ										0x00
#define CAN_BYTE_TO_SET_FAULT_ENABLE									0xC2
#define CAN_BYTE_TO_SET_OPERATION_CONDITION_ENABLE						0xC3

		// Argument Conatants
#define MODE_1															0x01
#define CAN_BYTE_TO_DISABLE_FOLDBACK									0x00
#define CAN_BYTE_TO_ENABLE_FOLDBACK_FROM_CC								0x01
#define CAN_BYTE_TO_ENABLE_FOLDBACK_FROM_CV								0x02
#define CAN_BYTE_TO_BRING_PSU_TO_LOCAL									0x00
#define CAN_BYTE_TO_BRING_PSU_TO_REMOTE									0x01
#define CAN_BYTE_TO_LOCKOUT_LOCAL										0x02
#define	CAN_AUTO_RESTART_BYTE											0x01
#define	CAN_SAFE_START_BYTE												0x00

		// Response Related Bytes
#define	CAN_FOLDBACK_OFF_BYTE											0x00
#define	CAN_FOLDBACK_CC_BYTE											0x01
#define CAN_FOLDBACK_CV_BYTE											0x02
#define CAN_PSC_OFF_BYTE												0x00
#define CAN_PSC_ON_BYTE													0x01
#define CAN_CV_MODE_BYTE												0x01
#define CAN_CC_MODE_BYTE												0x02
#define	CAN_PSU_IN_LOCAL_BYTE											0x00	
#define	CAN_PSU_IN_REMOTE_BYTE											0x01
#define	CAN_PSU_IN_LOCKOUT_BYTE											0x02
#define	CAN_PSU_MASTER_BYTE												0x00
#define	CAN_PSU_SLAVE_BYTE												0x01
#define	CAN_SRQ_DISABLED_BYTE											0x00
#define	CAN_SRQ_ENABLED_BYTE											0x01

		// Query Related Bytes
#define CAN_BYTE_TO_QUERY_PROGRAMMED_PARAMETERS							(CAN_BASE_ID_FOR_RESPONSE_TO_QUERIES + RESPONSE_MBOX_PROGRAMMED_PARAMS_EXTENSION)
#define CAN_BYTE_TO_QUERY_OUTPUT_PARAMETERS								(CAN_BASE_ID_FOR_RESPONSE_TO_QUERIES + RESPONSE_MBOX_OUTPUT_PARAMS_EXTENSION)
#define CAN_BYTE_TO_QUERY_RATED_PARAMETERS								(CAN_BASE_ID_FOR_RESPONSE_TO_QUERIES + RESPONSE_RATED_PARAMS_EXTENSION)
#define CAN_BYTE_TO_QUERY_SPECIFIED_PARAMETERS							(CAN_BASE_ID_FOR_RESPONSE_TO_QUERIES + RESPONSE_SPECIFIED_PARAMS_EXTENSION)
#define CAN_BYTE_TO_QUERY_SET_LIMITS									(CAN_BASE_ID_FOR_RESPONSE_TO_QUERIES + RESPONSE_MBOX_SET_LIMITS_EXTENSION)
#define CAN_BYTE_TO_QUERY_V_CAL_PARAMETERS								(CAN_BASE_ID_FOR_RESPONSE_TO_QUERIES + RESPONSE_MBOX_VOLTAGE_CAL_PARAMS_EXTENSION)
#define CAN_BYTE_TO_QUERY_I_CAL_PARAMETERS								(CAN_BASE_ID_FOR_RESPONSE_TO_QUERIES + RESPONSE_MBOX_CURRENT_CAL_PARAMS_EXTENSION)
#define CAN_BYTE_TO_QUERY_VDISPLAY_CAL_PARAMETERS						(CAN_BASE_ID_FOR_RESPONSE_TO_QUERIES + RESPONSE_MBOX_VOLTAGE_DISPLAY_CAL_PARAMS_EXTENSION)
#define CAN_BYTE_TO_QUERY_IDISPLAY_CAL_PARAMETERS						(CAN_BASE_ID_FOR_RESPONSE_TO_QUERIES + RESPONSE_MBOX_CURRENT_DISPLAY_CAL_PARAMS_EXTENSION)
#define CAN_BYTE_TO_QUERY_STATE_SET_1									(CAN_BASE_ID_FOR_RESPONSE_TO_QUERIES + RESPONSE_PSU_STATE_SET_1_EXTENSION)
#define CAN_BYTE_TO_QUERY_STATE_SET_2									(CAN_BASE_ID_FOR_RESPONSE_TO_QUERIES + RESPONSE_PSU_STATE_SET_2_EXTENSION)
#define CAN_BYTE_TO_QUERY_INTERNAL_PSU_REGISTERS						(CAN_BASE_ID_FOR_RESPONSE_TO_QUERIES + RESPONSE_INTERNAL_PSU_REGISTERS_EXTENSION)
#define CAN_BYTE_TO_QUERY_ENABLE_REGISTERS								(CAN_BASE_ID_FOR_RESPONSE_TO_QUERIES + RESPONSE_ENABLE_REGISTERS_EXTENSION)
#define CAN_BYTE_TO_QUERY_EVENT_REGISTERS								(CAN_BASE_ID_FOR_RESPONSE_TO_QUERIES + RESPONSE_EVENT_REGISTERS_EXTENSION)
#define CAN_BYTE_TO_QUERY_ONBOARD_AMBIENT_TEMP							(CAN_BASE_ID_FOR_RESPONSE_TO_QUERIES + RESPONSE_MBOX_PSU_ONBOARD_TEMPERATURE_EXTENSION)
#define CAN_BYTE_TO_QUERY_DATE_OF_CALIBRATION							(CAN_BASE_ID_FOR_RESPONSE_TO_QUERIES + RESPONSE_DATE_OF_CALIBRATION)
#define CAN_BYTE_TO_QUERY_FIRMWARE_REVISON								(CAN_BASE_ID_FOR_RESPONSE_TO_QUERIES + RESPONSE_FIRMWARE_REVISION)

		// Calibration Related Bytes -- 0xFX
#define CAN_BYTE_TO_SET_VOLTAGE_ZERO									0xF1
#define CAN_BYTE_TO_SET_VOLTAGE_FULL									0xF2
#define CAN_BYTE_TO_SET_CURRENT_ZERO									0xF3
#define CAN_BYTE_TO_SET_CURRENT_FULL									0xF4
#define CAN_BYTE_TO_RESET_CALIBRATION									0xF0

		// Error Signalling Bytes
#define CAN_BYTE_FOR_SUCCESSFULL_COMMAND								0x0F
#define CAN_BYTE_FOR_ILLEGAL_COMMAND									0xC1
#define CAN_BYTE_FOR_SINGLE_BYTE_MATCH_ERROR							0xC4
#define CAN_BYTE_FOR_SETTING_OUTSIDE_RANGE								0xC5
#define CAN_BYTE_FOR_UNSUPPORTED_MSG_ID									0xC6
#define CAN_BYTE_FOR_DATA_LENGTH_MISMATCH								0xC7
#define CAN_BYTE_FOR_SETTING_ABOVE_OVP									0xE1
#define CAN_BYTE_FOR_SETTING_BELOW_UVL									0xE2
#define CAN_BYTE_FOR_UNSUPPORTED_CALIBRATION_COMMANDS					0xE3
#define CAN_BYTE_FOR_ILLEGAL_OVP_SETTING								0xE4
#define CAN_BYTE_FOR_ILLEGAL_GAIN_CALCULATED							0xE5
#define CAN_BYTE_FOR_ILLEGAL_UVL_SETTING								0xE6
#define CAN_BYTE_TO_INDICATE_OUTPUT_CANNOT_SWITCH_ON					0xE7

// Can Data length constants
#define ENARKA_GLOBAL_BYTE_COMMANDS_DATA_LENGTH							2
#define PSU_GLOBAL_BYTE_COMMANDS_DATA_LENGTH							2
#define GLOBAL_BYTE_COMMANDS_DATA_LENGTH								2
#define PROGRAM_VOLT_DATA_LENGTH										4
#define PROGRAM_CURR_DATA_LENGTH										4
#define OUTPUT_CONTROL_BYTE_COMMANDS_DATA_LENGTH						2
#define STATE_CONTROL_BYTE_COMMANDS_DATA_LENGTH							2
#define QUERY_BYTE_DATA_LENGTH											2
#define CAL_BYTE_COMMAND_DATA_LENGTH									2
#define CAL_MEASURED_PARAMTERS_DATA_LENGTH								4
#define CAL_DATE_PARAMETER_DATA_LENGTH									3
#define FAULT_STATUS_QUERY_LENGTH                                       2
// Response key for Byte command processing
#define ENARKA_GLOBAL_BYTE_COMMANDS										0
#define PSU_GLOBAL_BYTE_COMMANDS										1
#define PSU_GLOBAL_BYTE_COMMANDS_WITH_ARG								2
#define OUTPUT_CONTROL_BYTE_COMMANDS									3
#define OUTPUT_CONTROL_BYTE_COMMANDS_WITH_ARG							4
#define STATE_CONTROL_BYTE_COMMANDS										5
#define STATE_CONTROL_BYTE_COMMANDS_WITH_ARG							6
#define QUERY_BYTES														7
#define CALIBRATION_BYTE_COMMANDS										8

// Datakey for parameter processing
#define MIN_VALUE		1
#define MAX_VALUE		2
#define MBOX_VALUE		3

// Calibration function Response Key
#define SET_CALIBRATION_DATE		0
#define SET_SPECIFIED_VALUES		1
#define CALIBRATE_VOLTAGE			2
#define CALIBRATE_CURRENT			3


#endif /*CAN_MODULEDEFS_H_*/
